# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwaizJk_gOqIIO_IQhe6BAJsWUhZy5GI
"""

import pandas as pd
df=pd.read_csv("/content/FuelConsumption .csv")
print("First 5 rows of the dataset:")
print(df.head())
print("\ncolumn names:")
print(df.columns.tolist())
print("\nshape of the dataset(rows,columns):",df.shape)
print("\ndata types")
print(df.dtypes)
print(":\nsummary stastics:")
print(df.describe(include='all'))
print("\nmissing values in each column:")
print(df.isnull().sum())
df_ffill = df.copy()
df_bfill = df.copy()
df_ffill = df.copy()
df_ffill['FUELCONSUMPTION_CITY'] = df_ffill['FUELCONSUMPTION_CITY'].fillna(method='ffill')
print("\nMissing Values after Forward Fill:")
print(df_ffill.isnull().sum())
df_bfill = df.copy()
df_bfill['FUELCONSUMPTION_CITY'] = df_bfill['FUELCONSUMPTION_CITY'].fillna(method='bfill')
print("\nMissing Values after Backward Fill:")
print(df_bfill.isnull().sum())
df_encoded = df.copy()
le = LabelEncoder()
df_encoded['VEHICLECLASS'] = le.fit_transform(df_encoded['VEHICLECLASS'])
print(df_encoded[['VEHICLECLASS']])
print(df_encoded[['VEHICLECLASS']].drop_duplicates())
print("\nCorrelation Matrix:")
print(df_encoded.corr())

from google.colab import drive
drive.mount('/content/drive')