# -*- coding: utf-8 -*-
"""ML EXP-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_0b5OX1nu59GdNhFNxC8Rd6mkSuYSfde
"""

#ADDITION OF TWO NUMBERS

a=1
b=2
c=(a+b)
print (c)

#EVEN OR ODD

num = int(input("Enter a number: "))
if num % 2 == 0:
    print(f"{num} is Even")
else:
    print(f"{num} is Odd")

#PRIME OR NOT

num = int(input("Enter a number: "))
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True
if is_prime(num):
    print(f"{num} is a prime number")
else:
    print(f"{num} is not a prime number")

#LARGEST OF FOUR NUMBERS

num1=1
num2=2
num3=3
num4=4
if num1 >= num2 and num1 >= num3 and num1 >= num4:
    largest_number = num1
elif num2 >= num1 and num2 >= num3 and num2 >= num4:
    largest_number = num2
elif num3 >= num1 and num3 >= num2 and num3 >= num4:
    largest_number = num3
else:
    largest_number = num4
print(f"The largest number is: {largest_number}")

#REVERSING A NUMBER

n = 4321
rev = 0
while n > 0:
    digit = n % 10
    rev = rev * 10 + digit
    n = n // 10
print(rev)

#PRINT A PATTERN

n = int(input("Enter the number: " ))
for i in range(1,n+1):
        print(i*"*")

#MULTLIPLICATION TABLE

n = int(input("Enter the table:"))
for i in range (1,11):
    print("1 X",n,"=",n*i)

#CALCULATOR

num1 = int(input("Num1: "))
num2 = int(input("Num2: "))

print("Sum: ",num1+num2)
print("Difference: ",num1-num2)
print("Product: ",num1*num2)
print("Quotient: ",num1/num2)
print("Remainder: ",num1%num2)
print("Exponent: ",num1**num2)

#PALLINDROME OR NOT

string1 = str(input("Enter the string: "))

if string1==string1[::-1]:
    print("It is Pallindrome")
else:
    print("It is not Pallindrome")

#SUM OF THE DIGITS

number = input("Enter a number: ")
digit_sum = sum(int(digit) for digit in number)
print(f"The sum of the digits of {number} is {digit_sum}")

#FACTORIAL OF A NUMBER


num1 = int(input("Enter the number: "))
num2 =1
for i in range(1,num1+1,1):
    num2 = i*num2

print("Factorial of",num1,"is",num2)