# -*- coding: utf-8 -*-
"""ML exp 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pt5HTGannCac1nBJYKSpRyDaVyS0zOQl
"""

import pandas as pd
data = pd.read_csv("/content/spam (2).csv",encoding='windows-1252')

data.head()

data.tail()

data.info()

data.isnull().sum()

x=data['v2'].values

y=data['v1'].values

y.shape

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

x_train=cv.fit_transform(x_train)
x_test=cv.transform(x_test)

x_train.shape

type(x_train)

x_test.shape

from sklearn.svm import SVC
svc=SVC()
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)
y_pred

from sklearn import metrics
accuracy = metrics.accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)