# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwaizJk_gOqIIO_IQhe6BAJsWUhZy5GI
"""

import pandas as pd
df=pd.read_csv('/content/FuelConsumption (2) (1).csv')
print("First 5 rows of the dataset:")
print(df.head())
print("\ncolumn names:")
print(df.columns.tolist())
print("\nshape of the dataset(rows,columns):",df.shape)
print("\ndata types")
print(df.dtypes)
print(":\nsummary stastics:")
print(df.describe(include='all'))
print("\nmissing values in each column:")
print(df.isnull().sum())